{% set name = "pytest-httpserver" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4d357402ae7e141f3914ed7cd25f3e24746ae928792dad60053daee4feae81fc

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - werkzeug >=2.0.0

test:
  imports:
    - pytest_httpserver
    - pytest_httpserver.blocking_httpserver
    - pytest_httpserver.hooks
    - pytest_httpserver.httpserver
    - pytest_httpserver.pytest_plugin
  source_files:
    - tests
  requires:
    - pip
    - pytest >=7.1.3,<9.0.0
    - requests
    - types-requests
  commands:
    - pip check
    # test_wait_raise_assertion_false: assert 0.25004416704177856 == 0.1 ± 0.1
    - pytest tests --deselect=tests/test_wait.py::test_wait_raise_assertion_false

about:
  home: https://github.com/csernazs/pytest-httpserver
  dev_url: https://github.com/csernazs/pytest-httpserver
  doc_url: https://pytest-httpserver.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest-httpserver is a httpserver for pytest
  description: |
    This library is designed to help to test http clients without contacting
    the real http server.  In other words, it is a fake http server which is
    accessible via localhost can be started with the pre-defined expected
    http requests and their responses.




extra:
  recipe-maintainers:
    - duncanmmacleod
