{% set name = "pytest-httpserver" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dc3d82e1fe00e491829d8939c549bf4bd9b39a260f87113c619b9d517c2f8ff1

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - python
    - werkzeug >=2.0.0

# >       assert waiting.elapsed_time == approx(waiting_timeout, abs=waiting_time_error)
# E       assert 0.2490883330174256 == 0.1 ± 0.1
{% set deselect_tests = " --deselect=tests/test_wait.py::test_wait_raise_assertion_false" %}

test:
  imports:
    - pytest_httpserver
    - pytest_httpserver.blocking_httpserver
    - pytest_httpserver.hooks
    - pytest_httpserver.httpserver
    - pytest_httpserver.pytest_plugin
  source_files:
    - tests
  requires:
    - pip
    - pytest >=7.1.3,<9.0.0
    - requests
    - types-requests
  commands:
    - pip check
    - pytest tests {{ deselect_tests }}

about:
  home: https://github.com/csernazs/pytest-httpserver
  dev_url: https://github.com/csernazs/pytest-httpserver
  doc_url: https://pytest-httpserver.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest-httpserver is a httpserver for pytest
  description: |
    This library is designed to help to test http clients without contacting
    the real http server.  In other words, it is a fake http server which is
    accessible via localhost can be started with the pre-defined expected
    http requests and their responses.

extra:
  recipe-maintainers:
    - duncanmmacleod
