{% set name = "pytest-httpserver" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: af819d6b533f84b4680b9416a5b3f67f1df3701f1da54924afd4d6e4ba5917ec

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - python
    - werkzeug >=2.0.0

test:
  imports:
    - pytest_httpserver
    - pytest_httpserver.blocking_httpserver
    - pytest_httpserver.hooks
    - pytest_httpserver.httpserver
    - pytest_httpserver.pytest_plugin
  source_files:
    - tests
  requires:
    - pip
    - pytest >=7.1.3,<9.0.0
    - requests
    - types-requests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/csernazs/pytest-httpserver
  dev_url: https://github.com/csernazs/pytest-httpserver
  doc_url: https://pytest-httpserver.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pytest-httpserver is a httpserver for pytest
  description: |
    This library is designed to help to test http clients without contacting
    the real http server.  In other words, it is a fake http server which is
    accessible via localhost can be started with the pre-defined expected
    http requests and their responses.

extra:
  recipe-maintainers:
    - duncanmmacleod